import os
import uuid
from typing import List, Optional

from fastapi import APIRouter, File, UploadFile, HTTPException, Header, Form
from ..auth import verify_id_token, db
from firebase_admin import firestore
from google.cloud import vision_v1
from google.cloud import storage
from dotenv import load_dotenv
import google.generativeai as genai
from pydantic import BaseModel

# --- Configuration ---
load_dotenv()
GCS_BUCKET_NAME = "whatif-backend-462323.firebasestorage.app"

# Configure AI and clients
genai.configure(api_key=os.getenv("GOOGLE_GENAI_API_KEY"))
vertex_model = genai.GenerativeModel(model_name="models/gemini-1.5-flash")
vision_client = vision_v1.ImageAnnotatorClient()
storage_client = storage.Client()

router = APIRouter()

# --- Helper Functions ---

def generate_scenario_story(prompt: str) -> str:
    full_prompt = f"Based on this memory: '{prompt}', generate an immersive 'What If' scenario story:"
    try:
        response = vertex_model.generate_content(full_prompt)
        return response.text if response.text else "[No content generated by AI]"
    except Exception as e:
        print(f"Generative AI story generation failed: {e}")
        return "[AI story generation failed due to an error]"

def upload_to_storage(file: UploadFile, user_id: str) -> str:
    try:
        blob_path = f"users/{user_id}/photos/{uuid.uuid4()}-{file.filename}"
        bucket = storage_client.bucket(GCS_BUCKET_NAME)  
        blob = bucket.blob(blob_path)
        blob.upload_from_file(file.file, content_type=file.content_type)
        blob.make_public()
        return blob.public_url
    except Exception as e:
        print(f"Storage upload error: {e}")
        raise HTTPException(status_code=500, detail="Failed to upload image to storage")


def get_image_labels(image_bytes: bytes) -> list:
    try:
        image = vision_v1.Image(content=image_bytes)
        response = vision_client.label_detection(image=image)
        if response.error.message:
            raise HTTPException(status_code=500, detail=f"Vision API error: {response.error.message}")
        return [label.description for label in response.label_annotations]
    except Exception as e:
        print(f"Vision AI error: {e}")
        raise HTTPException(status_code=500, detail="Failed to analyze image with Vision AI")

# --- Routes ---

@router.post("/")
async def create_scenario(
    photos: Optional[List[UploadFile]] = File(None),
    id_token: str = Header(...),
    title: str = Form(...),
    prompt: str = Form(...)
):
    try:
        user_id = verify_id_token(id_token)
        image_urls = []
        ai_labels = []
        original_filenames = []

        if photos:
            for photo in photos:
                content = await photo.read()
                labels = get_image_labels(content)
                ai_labels.extend(labels)
                photo.file.seek(0)
                url = upload_to_storage(photo, user_id)
                image_urls.append(url)
                original_filenames.append(photo.filename)

        ai_generated_story = generate_scenario_story(prompt)

        scenario_id = str(uuid.uuid4())
        scenario_data = {
            "user_id": user_id,
            "title": title,
            "prompt": prompt,
            "story": ai_generated_story,
            "imageUrls": image_urls,
            "original_filenames": original_filenames,
            "ai_labels": list(set(ai_labels)),
            "createdAt": firestore.SERVER_TIMESTAMP,
        }

        db.collection("scenarios").document(scenario_id).set(scenario_data)

        response_data = scenario_data.copy()
        response_data["id"] = scenario_id
        response_data.pop("createdAt", None)

        return response_data

    except Exception as e:
        print(f"Create scenario error: {e}")
        raise HTTPException(status_code=500, detail=f"Could not process request: {e}")

@router.get("/")
async def get_scenarios(id_token: str = Header(...)):
    try:
        user_id = verify_id_token(id_token)
        docs_stream = (
            db.collection("scenarios")
            .where("user_id", "==", user_id)
            .order_by("createdAt", direction=firestore.Query.DESCENDING)
            .stream()
        )

        scenarios = []
        for doc in docs_stream:
            scenarios.append({**doc.to_dict(), "id": doc.id})

        return scenarios

    except Exception as e:
        print(f"Fetch scenarios error: {e}")
        raise HTTPException(status_code=500, detail=f"Could not fetch scenarios: {e}")

class ScenarioUpdate(BaseModel):
    title: Optional[str] = None
    prompt: Optional[str] = None

@router.put("/{scenario_id}")
async def update_scenario(scenario_id: str, update_data: ScenarioUpdate, id_token: str = Header(...)):
    try:
        user_id = verify_id_token(id_token)
        doc_ref = db.collection("scenarios").document(scenario_id)
        doc = doc_ref.get()

        if not doc.exists:
            raise HTTPException(status_code=404, detail="Scenario not found")
        if doc.to_dict().get("user_id") != user_id:
            raise HTTPException(status_code=403, detail="Not authorized")

        update_fields = {}
        if update_data.title is not None:
            update_fields["title"] = update_data.title
        if update_data.prompt is not None:
            update_fields["prompt"] = update_data.prompt

        if not update_fields:
            raise HTTPException(status_code=400, detail="No valid fields provided for update.")

        doc_ref.update(update_fields)

        return {"message": f"Scenario {scenario_id} updated successfully"}

    except Exception as e:
        print(f"Update scenario error: {e}")
        raise HTTPException(status_code=500, detail=f"Could not update scenario: {e}")

@router.delete("/{scenario_id}")
async def delete_scenario(scenario_id: str, id_token: str = Header(...)):
    try:
        user_id = verify_id_token(id_token)
        doc_ref = db.collection("scenarios").document(scenario_id)
        doc = doc_ref.get()

        if not doc.exists:
            raise HTTPException(status_code=404, detail="Scenario not found")
        if doc.to_dict().get("user_id") != user_id:
            raise HTTPException(status_code=403, detail="Not authorized")

        scenario_data = doc.to_dict()
        if "imageUrls" in scenario_data and scenario_data["imageUrls"]:
            for url in scenario_data["imageUrls"]:
                try:
                    path_parts = url.split(f"/{GCS_BUCKET_NAME}/")
                    if len(path_parts) > 1:
                        blob_name = path_parts[1].split('?')[0]
                        bucket_obj = storage_client.bucket(GCS_BUCKET_NAME)
                        blob_obj = bucket_obj.blob(blob_name)
                        if blob_obj.exists():
                            blob_obj.delete()
                            print(f"Deleted GCS object: {blob_name}")
                except Exception as gcs_e:
                    print(f"Error deleting GCS object {url}: {gcs_e}")

        doc_ref.delete()
        return {"message": f"Scenario {scenario_id} deleted successfully"}

    except Exception as e:
        print(f"Delete scenario error: {e}")
        raise HTTPException(status_code=500, detail=f"Could not delete scenario: {e}")
